### ISSUE TITLE
What's the canonical way to do partial rebuilds?

### ISSUE THREAD

**Issue by bcherny** [wearefractal/gulp-coffee#58]
I have a directory of files, which I am compiling 1-to-1:

in:

```text
src/
|_ foo/
    |_ foo.coffee
|_ bar.coffee
```
out:

```text
dist/
|_ foo/
    |_ foo.js
|_ bar.js
```

What's the right way to watch and do partial rebuilds when a file changes (ie. only recompile the changed file)? An example would be nice.

**Comment by contra** [comment]
https://github.com/gulpjs/gulp#incremental-builds
