### ISSUE TITLE
why does gulp-coffee uglify the compiled *.js file under 'build/' using gulp-coffee

### ISSUE THREAD

**Issue by xiaoDC** [wearefractal/gulp-coffee#64]
coffee:
gulp.task 'coffee_build', ->
    gulp
    .src 'build/coffee/*.coffee'
    .pipe coffee bare: true
    .pipe gulp.dest "build/js/"

native:
gulp.task('coffee_build', function() {
  return gulp.src('build/coffee/*.coffee').pipe(coffee({
    bare: true
  })).pipe(gulp.dest("build/js/"));
});

**Comment by contra** [comment]
If your code is actually

```js
gulp.task('coffee_build', function() {
  return gulp.src('build/coffee/*.coffee')
    .pipe(coffee({
      bare: true
    }))
    .pipe(gulp.dest('build/js'));
});
```

then the files will be output to `build/js/whatever.coffee`

**Comment by xiaoDC** [comment]
thank you. I find the reason. It is the requirejs what does uglify the compiled js file !
